### ISSUE TITLE
Feature: catch specific OutOfMemory error

### ISSUE THREAD

**Issue by PatrickKutch** [PatrickKutch/Marvin#14]
and print appropriate message:
om.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182) at java.lang.Thread.run(Unknown Source) Caused by: java.lang.OutOfMemoryError: Java heap space at com.sun.javafx.iio.png.PNGImageLoader2.decodePalette(PNGImageLoader2.java:588) at com.sun.javafx.iio.png.PNGImageLoader2.load(PNGImageLoader2.java:669) at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:364) at com.sun.javafx.iio.ImageStorage.loadAll(ImageStorage.java:324) at com.sun.javafx.tk.quantum.PrismImageLoader2.loadAll(PrismImageLoader2.java:127) at com.sun.javafx.tk.quantum.PrismImageLoader2.(PrismImageLoader2.java:71) at com.sun.javafx.tk.quantum.QuantumToolkit.loadImage(QuantumToolkit.java:720) at javafx.scene.image.Image.loadImage(Image.java:1065) at javafx.scene.image.Image.initialize(Image.java:807) at javafx.scene.image.Image.(Image.java:621) at javafx.scene.image.ImageView.(ImageView.java:166) at kutch.biff.marvin.widget.DynamicImageWidget.setupImages(DynamicImageWidget.java:262) at kutch.biff.marvin.widget.DynamicImageWidget.Create(DynamicImageWidget.java:92) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.DynamicGridWidget.Create(DynamicGridWidget.java:74) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.GridWidget.Create(GridWidget.java:119) at kutch.biff.marvin.widget.TabWidget.Create(TabWidget.java:96) at kutch.biff.marvin.Marvin.SetupGoodies(Marvin.java:380) at kutch.biff.marvin.Marvin.start(Marvin.java:585) at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863) at com.sun.javafx.application.LauncherImpl$$Lambda$72/1093760236.run(Unknown Source) at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326) at com.sun.javafx.application.PlatformImpl$$Lambda$47/1766822961.run(Unknown Source) at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) at com.sun.javafx.application.PlatformImpl$$Lambda$50/1444729971.run(Unknown Source) at java.security.AccessController.doPrivileged(Native Method) at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)

**Comment by PatrickKutch** [comment]
Added - though not tested.
